- name: Create /data/docker directory
  tags: docker
  file:
    dest: "{{ realDockerDir }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=x,o=x"

- name: Bind mount /data/docker to /var/lib/docker
  tags: docker
  mount:
    path: /var/lib/docker
    src: "{{ realDockerDir }}"
    fstype: none
    opts: bind
    state: mounted

- name: Install Docker prequisite packages
  tags: docker
  apt:
    name: "{{ packages }}"
  vars:
   packages:
     - apt-transport-https
     - ca-certificates
     - software-properties-common

- name: Add Docker apt key by id from a keyserver
  tags: docker
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    
- name: Add Docker Repository
  tags: docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present    

- name: Install Docker packages
  tags: docker
  apt:
    name: "{{ packages }}"
  vars:
   packages:
     - docker-ce
